char const title[] = "xpaint";
unsigned long const SELECTION_OUTER_RADIUS_PX = 225;
unsigned long const SELECTION_INNER_RADIUS_PX = 40;
unsigned long const CANVAS_BACKGROUND_RGB = 0xAA0000;
unsigned long const CANVAS_DEFAULT_WIDTH = 500;
unsigned long const CANVAS_DEFAULT_HEIGHT = 800;
unsigned long const STATUSLINE_BACKGROUND_RGB = 0x000000;
unsigned long const STATUSLINE_FONT_RGB = 0xFFFFFF;
unsigned long const STATUSLINE_HEIGHT_PX = 10; // FIXME
unsigned long const WINDOW_BACKGROUND_RGB = 0x181818;
