.TH XPAINT 1 xpaint VERSION

.SH NAME
xpaint \- simple X paint

.SH SYNOPSIS
.B xpaint
.RB [\fIOPTIONS\fP]
.RB [\fIFILE\fP]

.SH DESCRIPTION

xpaint is used to interactively modify image files.

.SH POSITIONAL ARGUMENTS
.TP 12
\fIFILE\fP
Path or URI to local file to be modified.
.B Save
and
.B load
commands will refer to it.
Use "-" as path to read file from stdin and save to stdout.
Can be overwritten with \fI--input\fP and \fI--output\fP options.

.SH OPTIONS
.TP
.B \-\-help
Print help message.
.TP
.B \-V, \-\-version
Print version.
.TP
.B \-v, \-\-verbose
Use verbose output.
.TP
.B \-w \fIWIDTH\fP, \-\-width \fIWIDTH\fP
Set canvas width.
.TP
.B \-h \fIHEIGHT\fP, \-\-height \fIHEIGHT\fP
Set canvas height.
.TP
.B \-i \fIFILE\fP, \-\-input \fIFILE\fP
Set load file.
.TP
.B \-o \fIFILE\fP, \-\-output \fIFILE\fP
Set save file.

.SH USAGE

.SS MODES
Application can be in \fICOLOR\fP, \fICONSOLE\fP, \fIINTERACT\fP or \fITRANSFORM\fP modes.
Default mode is interact (\fI<Esc>\fP to enter),
it used to edit canvas.
Color mode (\fIc\fP to enter) is used to change color in current tool context.
Console mode (\fI:\fP to enter) is used to execute commands.
Transform mode (automatic enter with selection tool) is used to transform canvas or selected area.

.SS CONSOLE
In console mode all keys (except \fI<Esc>\fP) are captured to command line.
Use \fI<Enter>\fP to execute typed command,
use \fI<BS>\fP to delete typed letters.
Use \fI<Tab>\fP to request completions.
Completions will appear right after current command with different color.
Use \fI<Tab>\fP again to cycle completions,
use \fI<Enter>\fP to apply suggested completion.
Unicode are supported.
.TP
.B echo \fIMESSAGE\fP
Display message in statusline.
.TP
.B set \fIPROPERTY\fP \fIVALUE\fP
Set value to property.
Available properties:
line_w (tools line width),
col (tool context current color),
font (interface font, xft name),
inp (input file, pass "-" for stdin),
out (output file, pass "-" for stdout),
png_cmpr (PNG save file compression level),
jpg_qlty (JPG save file quality level),
spacing (brush spacing).
.TP
.B q
Exit program. No progress is saved.
.TP
.B save \fITYPE\fP [\fIFILE\fP]
Save canvas contents to file as png or jpg (\fITYPE\fP). \fIout\fP will be used if \fIFILE\fP not specified.
.TP
.B load [\fIFILE\fP]
Load png file to canvas. \fIinp\fP will be used if not specified.

.SS TOOL CONTEXT

Tool context holds tool and color list.
Available tool contexts are in left
corner of status line.
Change current tool context with number keys.
One tool context holds only one tool (default is pencil).
Color list can be modified in color mode.

.SS TOOLS
Tools used to manipulate canvas.
All actions can be undone/redone.
To change current tool hold right mouse and select needed tool in selection circle.

.TP
.B PENCIL
Draw squares and lines on left mouse. Hold shift to use last drawn point as line start.
.TP
.B BRUSH
Same as pencil but draws circles and can have spacing.
.TP
.B SELECTION
Select rectangular regions on canvas.
Move selected contents around the canvas by dragging with left mouse.
Clone selected contents to canvas by dragging with shift.
Copy selected contents to X selection via \fIC-c\fP.
.TP
.B FILL
Fill closed regions on canvas with current color.
.TP
.B PICKER
Copy selected color from canvas.
.TP
.B FIGURE
Draw circle, square or triangle.
Current figure can be changed in selection circle.
To change figure tool to another select pencil tool in selection circle.

.SS KEYBOARD COMMANDS (ACTIONS AND KEYS)
Actions are keybinds for which the modes in which they can be triggered can be customized.
All keybinds can be changed in \fIconfig.h\fP file (ACT_* and KEY_* variables).
Below are the default keys.

.TP
.B ACT_MODE_INTERACT <Esc>
Enter interact mode.
.TP
.B ACT_EXIT q
Exit program.
.TP
.B ACT_SAVE_TO_FILE <C-s>
Save canvas to output path.
Output path can be passed via \-\-output argument,
FILE positional argument, or via console.
Saved image type same as currently loaded file (PNG if no file loaded).
.TP
.B ACT_UNDO <C-z>
Undo action.
.TP
.B ACT_REVERT <C-Z>
Redo action.
.TP
.B ACT_COPY_AREA <C-c>
Own selection with contents of selection tool. Selection MIME is image/png.
.TP
.B ACT_PASTE_IMAGE <C-v>
Paste image from clipboard and enter transform mode.
.TP
.B ACT_SWAP_COLOR x
Swap current color with last used.
.TP
.B (no action) NUMBER FROM 0 TO 9
Change current tool context.
.TP
.B (no action) <C-Left>, <C-Right>, <C-Down>, <C-Up>
Resize canvas.
Use shift modifier to increase step.
.TP
.B ACT_ZOOM_IN(OUT) <C-+>(<C-->)
Zoom canvas in (out).

.TP
.B ACT_MODE_COLOR c
Enter color mode.
.TP
.B ACT_ADD_COLOR <C-Up>
In color mode. Increase color list length for current tool context.
.TP
.B ACT_TO_RIGHT(LEFT)_COL_DIGIT <Right>(<Left>)
In color mode. Move cursor to next (previous) digit in modified color.
.TP
.B (no action) NUMBER FROM 0 to F
In color mode. Change selected digit to typed.

.TP
.B ACT_MODE_CONSOLE :
Enter console mode.
.TP
.B (no action) LETTER (except ACT_MODE_INTERACT)
In console mode. Append letter to command.
.TP
.B KEY_CL_REQ_COMPLT <no default key>
In console mode. Display completions.
.TP
.B KEY_CL_NEXT_COMPLT <Tab>
In console mode. Cycle completions.
.TP
.B KEY_CL_APPLY_COMPLT <Return>
In console mode. Apply completions.
.TP
.B KEY_CL_RUN <Return>
In console mode. Run command.
.TP
.B KEY_CL_CLIPBOARD_PASTE <C-v>
In console mode. Paste from clipboard.
.TP
.B KEY_CL_ERASE_CHAR <BS>
In console mode. Clear letter from command.

.SS MOUSE COMMANDS
Mouse buttons also can be changed in \fIconfig.h\fP file (BTN_* variables).

.TP
.B BTN_MAIN <LeftMouse>
Use current tool.
.TP
.B BTN_SEL_CIRC <RightMouse>
Show tool selection circle. Hover tool icon and release button to select.
.TP
.B BTN_CANVAS_RESIZE <C-RightMouse>
Resize canvas using mouse.
.TP
.B BTN_SCROLL_DRAG <MiddleMouse>
Move canvas around on drag.
.TP
.B BTN_SCROLL_UP(DOWN, LEFT, RIGHT) <Up>(<Down>, <S-Up>, <S-Down>)
Scroll canvas around.
.TP
.B BTN_ZOOM_IN(OUT) <C-Up>(<C-Down>)
Zoom canvas in (out).
.TP
.B BTN_COPY_SELECITON <S-LeftMouse>
Make selection with selection tool and drag it with this button to copy area (instead of move).
.TP
.B BTN_TRANS_MOVE <LeftMouse>
Move canvas or selection in transform mode.
.TP
.B BTN_TRANS_RESIZE <RightMouse>
Scale canvas or selection in transform mode.
.TP
.B BTN_TRANS_RESIZE_PROPORTIONAL <S-RightMouse>
Scale canvas or selection in transform mode (maintain aspect ratio).
.TP
.B BTN_TRANS_ROTATE <C-S-RightMouse>
Rotate canvas or selection in transform mode by moving mouse along the y axis.

.SH NOTE
All listed keys are in vim notation.

.SH HOMEPAGE
https://github.com/Familex/xpaint
